sonic:
  agent:
    host: 127.0.0.1
    port: 7777
    key: 7bbc50da-1c7b-43e7-9d5d-4e8a86fa896a
  server:
    host: 127.0.0.1
    folder-port: 8094
    transport-port: 8095

modules:
  android:
    enable: true
  ios:
    enable: false
    wda-bundle-id: com.sonic.wda
    wda-ipa-name: sonic-wda.ipa
  webview:
    enable: false
    chrome-driver-debug-port: 7778
    chrome-driver-path: "/Applications/Google Chrome.app/Contents/MacOS/chromedriver"

spring:
  application:
    name: sonic-agent

rocketmq:
  name-server: 81.70.118.76:9876
  producer:
    # 消息超过4kb则压缩
    compress-message-body-threshold: 4096
    # 消息最大为4kb
    max-message-size: 4194304
    # 生产环境请配置ACL
    # 必须配置组，否则启动报错
    group: TEST_DATA_GROUP
  topic:
    # 测试任务topic
    test-task-topic: TEST_TASK_TOPIC
    # 测试数据topic
    test-data-topic: TEST_DATA_TOPIC
    # 任务超时topic
    timeout-test-topic: TIMEOUT_TEST_TOPIC
  group:
    # 测试任务group
    test-task-group: TEST_TASK_GROUP
    # 测试数据group
    test-data-group: TEST_DATA_GROUP
    # 任务超时group
    timeout-test-group: TIMEOUT_TEST_GROUP

logging:
  file:
    name: logs/sonic-agent.log
  logback:
    rollingpolicy:
      clean-history-on-start: true
      max-history: 3
