server:
  port: 7777

spring:
  application:
    name: sonic-agent
  rabbitmq:
    host: 81.70.118.76
    port: 5672
    username: guest
    password: guest
    virtual-host: sonic
    listener:
      simple:
        acknowledge-mode: manual
    publisher-confirm-type: correlated
    publisher-returns: true

logging:
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      clean-history-on-start: true
      max-history: 3

sonic:
  chrome:
    path: "/Applications/Google Chrome.app/Contents/MacOS/chromedriver"
  folder:
    url: http://localhost:8094/api/folder
  agent:
    host: 127.0.0.1
    key: 7bbc50da-1c7b-43e7-9d5d-4e8a86fa896a
